config/routes.rb
Signature::Application.routes.draw do
  resources :company_stamps

  resources :stamps

  get "home/index"

  devise_for :users, :path_names => {:sign_up => "register", :sign_in => "login", :sign_out => "logout"}
  namespace :company do
    resources :users # Have the admin manage them here.
  end
  root :to => "home#index"

end

app/models/stamp.rb
class Stamp < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :email
	has_one :setting, :class_name => "StampSetting"
	
	attr_writer :current_step
	
	def current_step
		@current_step || steps.first
	end
	
	def steps
		%w[email choose design]
	end
	
	def next_step
		self.current_step = steps[steps.index(current_step) + 1]
	end
	
	def previous_step
		self.current_step = steps[steps.index(current_step) - 1 ]
	end
	
	def first_step?
		current_step == steps.first
	end
	
	def last_step?
		current_step == steps.last
	end
	
	def self.templates
		@templates = []
    Dir.glob( File.join( Rails.root.to_s , 'public' ,'templates', 'sign_*', "*.html.erb") ).each do |template|
      @templates << template
    end
	end
	
	def self.template(name)
		File.join( Rails.root.to_s , 'public' ,'templates', "#{name}", "#{name}.html.erb") 
	end
end

app/controllers/stamps_controller.rb
class StampsController < ApplicationController
  # GET /stamps
  # GET /stamps.xml
  before_filter :authenticate_user!
  def index
    @stamps = current_user.stamps.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @stamps }
    end
  end

  # GET /stamps/1
  # GET /stamps/1.xml
  def show
    @stamp = current_user.stamps.find(params[:id])
    @css = @stamp.setting.settings
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @stamp }
      format.json { render :json => @stamp}
    end
  end

  # GET /stamps/new
  # GET /stamps/new.xml
  def new
    session[:sign_params] ||= {}
    @stamp = current_user.stamps.new(session[:sign_params])
    @stamp.current_step = session[:sign_step]
    @template_name = session[:sign_template]
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @stamp }
    end
  end

  # GET /stamps/1/edit
  def edit
    @stamp = current_user.stamps.find(params[:id])
  end

  # POST /stamps
  # POST /stamps.xml
  def create
    session[:sign_params].deep_merge!(params[:stamp]) if params[:stamp]
    session[:sign_template] = params[:stamp_template] if params[:stamp_template]
    @stamp = current_user.stamps.new(session[:sign_params])
    @stamp.current_step = session[:sign_step]
    @template_name = session[:sign_template]
    
    if @stamp.valid?
      if params[:back_button]
        @stamp.previous_step
      elsif @stamp.last_step?
        @stamp.save #if @order.all_valid?
      else
        @stamp.next_step
      end
      session[:sign_step] = @stamp.current_step
    end
    respond_to do |format|
      unless @stamp.new_record?
        @settings = StampSetting.create(:stamp_id => @stamp.id, :settings => JSON.parse(params[:settings].to_json))
        session[:sign_step] = session[:sign_params] = nil
        format.html { redirect_to(@stamp, :notice => 'Stamp was successfully created.') }
        format.xml  { render :xml => @stamp, :status => :created, :location => @stamp }
      else
        format.html { redirect_to(:action => "new") }
        format.xml  { render :xml => @stamp.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stamps/1
  # PUT /stamps/1.xml
  def update
    @stamp = current_user.stamps.find(params[:id])

    respond_to do |format|
      if @stamp.update_attributes(params[:stamp])
        @settings = @stamp.setting.update_attributes(:settings => JSON.parse(params[:settings].to_json))
        format.html { redirect_to(@stamp, :notice => 'Stamp was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @stamp.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stamps/1
  # DELETE /stamps/1.xml
  def destroy
    @stamp = current_user.stamps.find(params[:id])
    @stamp.destroy

    respond_to do |format|
      format.html { redirect_to(stamps_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/stamps_helper.rb
module StampsHelper
end

app/views/stamps/_choose_step.html.erb
<h1 class="heading bold">Choose the Signature Template</h1>
<br />
<br />
<% Stamp.templates.each do |file| %>

	<span>
		<%= radio_button_tag "stamp_template", File.basename(file,".html.erb") %>
		<%= render :file => file, :object =>  @stamp %>
	<span>
	<br />
	<hr />
	<br />
<% end %>

app/views/stamps/_design_step.html.erb
<h1 class="heading bold">Design your Signature </h1>
<br />
<br />
<div id="stamp_design" >
	<%= render :file => Stamp.template(@template_name), :object =>  @stamp %>
	<br />
	<br />
	<%= hidden_field :settings,  :stamp %>
	<%= hidden_field :settings,  :html %>
	<%= hidden_field :stamp,  :name %>
	<%= hidden_field :stamp, :designation %>
	<%= hidden_field :stamp, :company %>
	<%= hidden_field :stamp, :mobile %>
	<%= hidden_field :stamp, :email %>


</div>
<div style="position: relative;">
	<a id="text-editor-close-button" class="button" href="#"><span class="label"></span></a>
	<%= ckeditor_textarea("design", "area", :width => '100%', :height => '80px', :class => "hidden" ) %>
</div>
<%= javascript_include_tag "st-editor" %>

app/views/stamps/_email_step.html.erb
<h1 class="heading bold">Email Address </h1>
<br />
<br />
<p>
<%= f.label :email, "Enter your email address" %> <br />
<%= f.text_field :email, :value => @stamp.email.blank? ? current_user.email : @stamp.email %>
<br />
</p>

app/views/stamps/_form.html.erb
<%= form_for(@stamp) do |f| %>
  <% if @stamp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stamp.errors.count, "error") %> prohibited this stamp from being saved:</h2>

      <ul>
      <% @stamp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
	
	<div id="vsign_wrapper" class="vsign_wrapper resizable">
		<div class="vsign_top">
		</div>
		
		<div id="vsign_content" class="vsign_content resizable draggable absolute">
		
			<div id="vsign_name" class="vsign_name draggable absolute ten editable"><%= @stamp.name.blank? ? "Enter full name" : @stamp.name%></div>
			<br>
			<div id="vsign_email" class="vsign_email draggable absolute ten">
				<%= current_user.email%>
			</div>
			<br>
			<div id="vsign_mobile" class="vsign_name draggable absolute ten editable"><%= @stamp.mobile.blank? ? "Enter mobile number" : @stamp.mobile %></div>
			<br>
			<div id="vsign_links" class="vsign_links">
			
			</div>
			<!-- <div class="vsign_powered absolute" style="bottom: -15px; ">
							<a href="#"><span class="grey eight">signature powered by</span></a>
							<a href="#"><span class="grey nine bold">PeepSign</span></a>
						</div> -->
		</div>
			
		<div class="clear"></div>
	
		
		<div class="vsign_bottom">
			
		</div>
		<div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 1001; "></div>
		
	</div>
	
	
	
	
	
  <%= f.hidden_field :email, :value => current_user.email %></p>
  <%= f.hidden_field :name, :value => @stamp.name %></p>
  <%= f.hidden_field :mobile, :value => @stamp.mobile %></p>

	<%= hidden_field :settings, :stamp_email, :value => (@stamp.setting.settings["stamp_email"] unless @stamp.setting.blank?)%>
	<%= hidden_field :settings, :stamp_content, :value => (@stamp.setting.settings["stamp_content"] unless @stamp.setting.blank?) %>
	<%= hidden_field :settings, :stamp_name, :value => (@stamp.setting.settings["stamp_name"] unless @stamp.setting.blank?) %>
	<%= hidden_field :settings, :stamp_mobile, :value => (@stamp.setting.settings["stamp_mobile"] unless @stamp.setting.blank?) %>
	
	<%#= render :partial => 'stamp_email' %>

  <%#= render :partial => 'stamp_review' %>
	<br>
	<br>
  <div id="vsign_submit" class="actions right">
    <%= f.submit%>
  </div>
	<div class="clear"></div>
<% end %>

app/views/stamps/_show_design.html.erb
<div class="sig_boundary"> <!-- signature boundary -->

  <div class="sig_top">
  </div>

  <div class="sig_left" style="float:left;">
  </div>

  <div class="sig_wrapper">
    <div class="sig_col_one"> 
    
      <div class="sig_logo sign_text">
        Company Logo
      </div>
    
      <div class="sig_name sign_text">
        <%= @stamp.name %>
      </div>
      
      <div class="sig_designation sign_text">
        <%= @stamp.designation %>
      </div>
      
      <div class="sig_company sign_text">
        <%= @stamp.company %>
      </div>
      
      <div class="sig_mobile sign_text">
        <%= @stamp.mobile %>
      </div>
      
      <div class="sig_email">
        <%= @stamp.email %>
      </div>
      
    </div>

    <div class="sig_col_two">
      <div class="sig_message_board sign_image_link">
        Some Clickable Message to display
      </div>
  
    </div>

    <div class="sig_col_three">
      <ul class="sign_site_navigation_links sign_links">
        <li> <a href="#"> Home </a> </li>
        <li> <a href="#"> Product </a> </li>
        <li> <a href="#"> Careers </a> </li>
        <li> <a href="#"> Contact Us </a> </li>
      <ul>
    </div>
    <div style="clear:both;"></div>
  </div>
  <div style="clear:both;"></div>
  
  <div class="sig_right" style="float:right;">
  </div>

  <div style="clear:both;"></div>

  <div class="sig_bottom">
    <div class="sign_disclaimer sign_text">
    </div>
  </div>

</div> <!-- Signature boundary ended -->

app/views/stamps/_show_item.html.erb
<div id="vsign_wrapper_<%= @stamp.id %>" class="vsign_wrapper" style="position: relative;">
	<div class="vsign_top_<%= @stamp.id %>">
	</div>
	
	<div id="vsign_content_<%= @stamp.id %>" class="vsign_content absolute" data-css="<%= @stamp.setting.settings['stamp_content'] %>">
	
		<div id="vsign_name_<%= @stamp.id %>" class="vsign_name ten absolute" data-css="<%= @stamp.setting.settings['stamp_name'] %>"><%= @stamp.name.blank? ? "Enter full name" : @stamp.name%></div>
		<br>
		<div id="vsign_email_<%= @stamp.id %>" class="vsign_email absolute" data-css="<%= @stamp.setting.settings['stamp_email'] %>">
			<%= current_user.email%>
		</div>
		<br>
		<div id="vsign_mobile_<%= @stamp.id %>" class="vsign_name absolute ten" data-css="<%= @stamp.setting.settings['stamp_mobile'] %>"><%= @stamp.mobile.blank? ? "Enter mobile number" : @stamp.mobile %></div>
		<br>
		<div id="vsign_links_<%= @stamp.id %>" class="vsign_links">
		
		</div>
		<div class="vsign_powered absolute" style="bottom: -15px; ">
			<a href="#"><span class="grey eight">signature powered by</span></a>
			<a href="#"><span class="grey nine bold">PeepSign</span></a>
		</div>
	</div>
		
	<div class="clear"></div>

	
	<div class="vsign_bottom_<%= @stamp.id %>">
		
	</div>	
</div>

<script type="text/javascript" charset="utf-8">
	showElementPosition($("#vsign_content_<%= @stamp.id %>"));
	showElementPosition($("#vsign_name_<%= @stamp.id %>"));
	showElementPosition($("#vsign_email_<%= @stamp.id %>"));
	showElementPosition($("#vsign_mobile_<%= @stamp.id %>"));
</script>

app/views/stamps/edit.html.erb
<h1 class="heading bold">Edit your signature</h1>
<br>
<br>
<%= render 'form' %>

<%= link_to 'Show', @stamp %> |
<%= link_to 'Back', stamps_path %>

app/views/stamps/index.html.erb
<h1 class="heading bold">Listing Signatures</h1>
<br>
<br>
<% @stamps.each do |@stamp| %>
	<br>
	<%= render :partial => 'show_design' %>
	<br>
	<%= link_to 'Edit', edit_stamp_path(@stamp) %> |
	<%= link_to 'Back', stamps_path %>
	<br>
<% end %>

app/views/stamps/new.html.erb
<%= form_for @stamp do |f| %>
 <% if @stamp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stamp.errors.count, "error") %> prohibited this stamp from being saved:</h2>

      <ul>
      <% @stamp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= render "#{@stamp.current_step}_step", :f => f %>
  <p><%= f.submit "Continue" %></p>
  <p><%= f.submit "Back", :name => "back_button" unless @stamp.first_step? %></p>
<% end %>

app/views/stamps/show.html.erb
<p id="notice"><%= notice %></p>
<%#= render :partial => 'show_item' %>
<%= render :partial => 'show_design' %>
<%= link_to 'Edit', edit_stamp_path(@stamp) %> |
<%= link_to 'Back', stamps_path %>