config/routes.rb
Signature::Application.routes.draw do
  resources :company_stamps

  resources :stamps

  get "home/index"

  devise_for :users, :path_names => {:sign_up => "register", :sign_in => "login", :sign_out => "logout"}
  namespace :company do
    resources :users # Have the admin manage them here.
  end
  root :to => "home#index"

end

app/models/company_stamp.rb
class CompanyStamp < ActiveRecord::Base
end

app/controllers/company_stamps_controller.rb
class CompanyStampsController < ApplicationController
  # GET /company_stamps
  # GET /company_stamps.xml
  def index
    @company_stamps = CompanyStamp.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @company_stamps }
    end
  end

  # GET /company_stamps/1
  # GET /company_stamps/1.xml
  def show
    @company_stamp = CompanyStamp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @company_stamp }
    end
  end

  # GET /company_stamps/new
  # GET /company_stamps/new.xml
  def new
    @company_stamp = CompanyStamp.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @company_stamp }
    end
  end

  # GET /company_stamps/1/edit
  def edit
    @company_stamp = CompanyStamp.find(params[:id])
  end

  # POST /company_stamps
  # POST /company_stamps.xml
  def create
    @company_stamp = CompanyStamp.new(params[:company_stamp])

    respond_to do |format|
      if @company_stamp.save
        format.html { redirect_to(@company_stamp, :notice => 'Company stamp was successfully created.') }
        format.xml  { render :xml => @company_stamp, :status => :created, :location => @company_stamp }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @company_stamp.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /company_stamps/1
  # PUT /company_stamps/1.xml
  def update
    @company_stamp = CompanyStamp.find(params[:id])

    respond_to do |format|
      if @company_stamp.update_attributes(params[:company_stamp])
        format.html { redirect_to(@company_stamp, :notice => 'Company stamp was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @company_stamp.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /company_stamps/1
  # DELETE /company_stamps/1.xml
  def destroy
    @company_stamp = CompanyStamp.find(params[:id])
    @company_stamp.destroy

    respond_to do |format|
      format.html { redirect_to(company_stamps_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/company_stamps_helper.rb
module CompanyStampsHelper
end

app/views/company_stamps/_form.html.erb
<%= form_for(@company_stamp) do |f| %>
  <% if @company_stamp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company_stamp.errors.count, "error") %> prohibited this company_stamp from being saved:</h2>

      <ul>
      <% @company_stamp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/company_stamps/edit.html.erb
<h1>Editing company_stamp</h1>

<%= render 'form' %>

<%= link_to 'Show', @company_stamp %> |
<%= link_to 'Back', company_stamps_path %>

app/views/company_stamps/index.html.erb
<h1>Listing company_stamps</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @company_stamps.each do |company_stamp| %>
  <tr>
    <td><%= link_to 'Show', company_stamp %></td>
    <td><%= link_to 'Edit', edit_company_stamp_path(company_stamp) %></td>
    <td><%= link_to 'Destroy', company_stamp, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company stamp', new_company_stamp_path %>

app/views/company_stamps/new.html.erb
<h1>New company_stamp</h1>

<%= render 'form' %>

<%= link_to 'Back', company_stamps_path %>

app/views/company_stamps/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_company_stamp_path(@company_stamp) %> |
<%= link_to 'Back', company_stamps_path %>