config/routes.rb
Signature::Application.routes.draw do
  resources :company_stamps

  resources :stamps

  get "home/index"

  devise_for :users, :path_names => {:sign_up => "register", :sign_in => "login", :sign_out => "logout"}
  namespace :company do
    resources :users # Have the admin manage them here.
  end
  root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Signature</title>
  <%= stylesheet_link_tag :all%>
  <%= javascript_include_tag :defaults, "jquery-json.js", "jquery-jeditable.js" %>
  <%= javascript_include_tag :ckeditor %>
  <%= csrf_meta_tag %>
</head>
<body>
		<div class="top-wrapper">
		<div class="menuhead">
			<div class="top-inline">
				<div class="top-img bold">
					Peep<span class="yellow">Sign</span>
				</div>
				<div class="headerlink">
	          <ul>
	              <li>
									<a class="" href="/"> Home </a>
									<span><img src="/images/footer-seperator.gif" height="12px" width="2px" title="" /></span>
								</li>
	              <li>
									<a class="" href="#"> Product </a>
									<span><img src="/images/footer-seperator.gif" height="12px" width="2px" title="" /></span>
								</li>
								<li>
									<a class="" href="#"> Blog </a>
									<span><img src="/images/footer-seperator.gif" height="12px" width="2px" title="" /></span>
								</li>
								<li>
									<a class="" href="#"> About Us </a>
									<span><img src="/images/footer-seperator.gif" height="12px" width="2px" title="" /></span>
								</li>
								<li>
									<a class="" href="#">	Contact Us </a><span>
								</li>
	          </ul>
	      </div>
				<div class="top-right">
					<% if user_signed_in? %>  
				    <%= current_user.email %> |
				    <span><%= link_to "Sign out", destroy_user_session_path %></span>
					<% else %>
					  <span><%= link_to "Login", new_user_session_url %></span>
						<span><img src="/images/footer-seperator.gif" height="12px" width="2px" title="" /></span>
					 	<span><%= link_to "Register", new_user_registration_url %></span>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<div class="clear"></div>

	<div class="content-top">
		<% if notice %>
	  	<p class="notice"><%= notice %></p>
		<% end%>
		<% if alert %>
	  	<p class="alert"><%= alert %></p>
		<% end %>
	</div>
	<div class="content-wrapper">
		<% if current_user %>
			<div class="right_user_links">
				<div class="my_signature_link">
					<%= link_to "My Signatures", stamps_url %>
				</div>
				<div class="create_new_signature">
					<%= link_to "Create new signature", new_stamp_url %>
				</div>
			</div>
			<script type="text/javascript" charset="utf-8">
				$(function() {
						$( "a", ".my_signature_link" ).button();
						$( "a", ".create_new_signature" ).button();
						//$( "a", ".my_signature_link" ).click(function() { $.post("/users");});
						//$( "a", ".create_new_signature" ).click(function() { return false; });
					});
			</script>
			<div class="clear"></div>
		<% end%>
		<div class="clear"> </div>
		<div class="content">
		  <%= yield %>
		</div>
	</div>
	<div class="clear"></div>
	
	<div class="footer-top-wrapper">
		<div class="footer-wrapper">
			<div class="footer-inline">
				<div class="footer-img bold">
					Peep<span class="yellow">Sign</span>
				</div>
				<div class="footerlink">
	          <ul>
	              <li>
									<a class="" href=""> About Us </a>
									<span><img src="/images/footer-seperator.gif" height="12px" width="2px" title="" /></span>
								</li>
								<li>
									<a class="" href="#"> Privacy Policy </a>
									<span><img src="/images/footer-seperator.gif" height="12px" width="2px" title="" /></span>
								</li>
								<li>
									<a class="" href="#"> FAQ </a>
									<span><img src="/images/footer-seperator.gif" height="12px" width="2px" title="" /></span>
								</li>
								<li>
									<a class="" href="#">	Contact Us </a><span>
								</li>
	          </ul>
	              <p class="footer_txt">Copyright &copy; 2010 PeepSign. All rights reserved.</p>
	        </div>
			</div>
		</div>
	</div>
	<div class="clear"></div>
</body>
</html>